openapi: 3.0.3
info:
  title: FastAPI Demo
  version: "1.0.0"
paths:
  /health:
    get:
      summary: Health
      operationId: health
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: ok }
                  message: { type: string, example: Hello PyCon! }
  /score:
    get:
      summary: Score text
      operationId: score
      parameters:
        - in: query
          name: text
          schema: { type: string, minLength: 1 }
          required: true
          description: Text to score
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  text: { type: string }
                  score: { type: integer, minimum: 0, maximum: 9 }
